language: php

sudo: false

php:
  - 7.0
  - hhvm

env:
  global:
    - COMPOSER_ADDITIONAL_ARGS=""

matrix:
  include:
    - php: 7.0
      env:
        - DEPENDENCIES=""
    - php: 7.0
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: hhvm
      env:
        - DEPENDENCIES=""
        - COMPOSER_ADDITIONAL_ARGS="--ignore-platform-reqs"
    - php: hhvm
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - COMPOSER_ADDITIONAL_ARGS="--ignore-platform-reqs"
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES $COMPOSER_ADDITIONAL_ARGS

script:
  - if [ "$TRAVIS_PHP_VERSION" = '7.0' ] ; then ./vendor/bin/phpunit --coverage-clover ./clover.xml; fi;
  - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ] ; then ./vendor/bin/phpunit --coverage-clover ./clover.xml -v Eval.EnableHipHopSyntax=true; fi;
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = '7.0' ] ; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi;

notifications:
  irc: "irc.freenode.org#zftalk.modules"
